// frontend-vue/src/pages/KnowledgeList.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useRouter } from 'vue-router';
import { Edit, Trash2, Plus, BookOpen, Clock, ChevronRight, Loader2, ChevronLeft } from 'lucide-vue-next';
import { useI18n } from 'vue-i18n';
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query';
import axios from 'axios';
import type { Knowledge, PageResponse } from '@/types';

// ナレッジの一覧とページネーションを表示するトップページコンポーネント
const API_URL = 'http://localhost:8080/api/knowledge';
const { t } = useI18n();
const router = useRouter();
const queryClient = useQueryClient();

// 現在のページ番号（0始まり）を保持するリアクティブ状態
const page = ref(0);

// 指定ページのナレッジ一覧を取得するAPI呼び出し関数
const fetchKnowledges = async (p: number): Promise<PageResponse<Knowledge>> => {
  const response = await axios.get(`${API_URL}?page=${p}&size=6&sort=createdAt,desc`);
  return response.data;
};

// Vue Query を用いて一覧データを取得し、ローディングやキャッシュを管理する処理
const { data, isLoading, isError, isPlaceholderData } = useQuery({
  queryKey: ['knowledges', page],
  queryFn: () => fetchKnowledges(page.value),
  placeholderData: (prev) => prev,
});

// クエリ結果から表示用の配列と総ページ数を算出する算出プロパティ
const knowledges = computed(() => data.value?.content || []);
const totalPages = computed(() => data.value?.totalPages || 0);

// 削除処理を行うミューテーション定義であり、成功時に一覧キャッシュを無効化する設定
const deleteMutation = useMutation({
  mutationFn: async (id: number) => {
    await axios.delete(`${API_URL}/${id}`);
  },
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['knowledges'] });
  },
});

// カード内の削除ボタン押下時にイベント伝播を止めつつ削除確認を行うハンドラ関数
const handleDelete = (e: MouseEvent, id: number) => {
  e.stopPropagation();
  if (!window.confirm(t('common.confirm_delete'))) return;
  deleteMutation.mutate(id);
};

// 編集ボタン押下時にカードクリックと競合しないよう伝播を止めつつ編集画面へ遷移するハンドラ関数
const handleEdit = (e: MouseEvent, id: number) => {
  e.stopPropagation();
  router.push(`/edit/${id}`);
};

// Markdownの装飾を簡易的に除去しつつ、指定文字数でサマリを生成するユーティリティ関数
const getExcerpt = (text: string, maxLength: number = 150) => {
  const plainText = text.replace(/[#*`[\]()]/g, '');
  if (plainText.length <= maxLength) return plainText;
  return plainText.substring(0, maxLength) + '...';
};

// ページ番号を更新して再フェッチをトリガーするための関数
const setPage = (p: number) => {
  page.value = p;
};
</script>

<template>
  <div class="max-w-6xl mx-auto">
    <!-- ページ上部のヘッダーエリア -->
    <div class="flex items-center justify-between mb-10 px-2">
      <h2 class="text-3xl font-black text-[#0d3b3b] flex items-center gap-3">
        <span class="p-2 bg-[#1a7a7a] rounded-xl text-white shadow-lg shadow-teal-200">
          <BookOpen :size="28" />
        </span>
        {{ t('knowledge.list_title') }}
      </h2>
      
      <div class="flex items-center gap-4">
        <div class="flex items-center gap-2 px-4 py-2 bg-white rounded-full border border-teal-100 shadow-sm">
          <span class="w-2 h-2 bg-[#1a7a7a] rounded-full animate-pulse"></span>
          <span class="text-[#1a7a7a] text-sm font-black">
            {{ data?.totalElements || 0 }} <span class="text-xs font-bold text-[#4a6b6b]">{{ t('knowledge.items_count') }}</span>
          </span>
        </div>
        
        <button
          @click="router.push('/new')"
          class="flex items-center gap-2 px-6 py-2.5 bg-[#1a7a7a] hover:bg-[#0d3b3b] text-white rounded-xl font-bold transition-all shadow-lg shadow-teal-100 active:scale-95"
        >
          <Plus :size="20" /> {{ t('sidebar.new_create') }}
        </button>
      </div>
    </div>

    <!-- 読み込み中・エラー時の表示 -->
    <div v-if="isLoading" class="flex flex-col items-center justify-center py-32 text-[#1a7a7a]">
      <Loader2 :size="48" class="animate-spin mb-4" />
      <p class="font-bold">{{ t('common.loading') }}</p>
    </div>
    
    <div v-else-if="isError" class="text-center py-32 bg-rose-50 rounded-[3rem] border-2 border-rose-100">
      <p class="text-rose-600 font-bold text-xl">データの取得に失敗しました。</p>
    </div>
    
    <div v-else-if="knowledges.length === 0" class="text-center py-32 bg-white rounded-[3rem] border-4 border-dashed border-teal-50">
      <div class="text-7xl mb-6 opacity-20">🍃</div>
      <p class="text-[#4a6b6b] font-bold text-2xl">{{ t('knowledge.no_items') }}</p>
      <p class="text-slate-400 text-lg mt-3 font-medium">{{ t('knowledge.no_items_desc') }}</p>
      <button
        @click="router.push('/new')"
        class="mt-8 px-8 py-3 bg-teal-50 text-[#1a7a7a] rounded-2xl font-black hover:bg-teal-100 transition-all"
      >
        {{ t('knowledge.first_create') }}
      </button>
    </div>

    <div v-else class="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <div 
        v-for="k in knowledges" 
        :key="k.id" 
        @click="router.push(`/knowledge/${k.id}`)"
        class="group bg-white rounded-[2.5rem] p-8 shadow-xl shadow-teal-900/5 border border-teal-50 hover:border-[#1a7a7a]/20 hover:shadow-2xl hover:shadow-teal-900/10 transition-all duration-500 flex flex-col relative overflow-hidden cursor-pointer"
      >
        <div class="absolute top-0 right-0 w-40 h-40 bg-teal-50/30 rounded-full -mr-20 -mt-20 group-hover:scale-110 transition-transform duration-700"></div>
        
        <div class="flex-grow relative z-10">
          <h3 class="text-2xl font-black text-[#0d3b3b] mb-4 group-hover:text-[#1a7a7a] transition-colors line-clamp-2 leading-tight">
            {{ k.title }}
          </h3>
          <p class="text-[#4a6b6b] leading-relaxed mb-6 line-clamp-3 font-medium text-sm">
            {{ getExcerpt(k.content) }}
          </p>
          <div class="flex items-center gap-1 text-[#1a7a7a] font-bold text-sm mb-8 group-hover:gap-2 transition-all">
            {{ t('knowledge.view_detail') }} <ChevronRight :size="16" />
          </div>
        </div>
        
        <div class="mt-auto pt-6 border-t border-teal-50 relative z-10 flex items-center justify-between">
          <div class="flex items-center gap-2 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">
            <Clock :size="12" />
            {{ k.createdAt ? new Date(k.createdAt).toLocaleDateString('ja-JP') : '-' }}
          </div>
          
          <div class="flex gap-2">
            <button
              @click="handleEdit($event, k.id!)"
              class="p-2.5 rounded-xl bg-amber-50 text-amber-700 hover:bg-amber-100 transition-all"
              :title="t('common.edit')"
            >
              <Edit :size="16" />
            </button>
            <button
              @click="handleDelete($event, k.id!)"
              class="p-2.5 rounded-xl bg-rose-50 text-red-600 hover:bg-rose-100 transition-all"
              :title="t('common.delete')"
            >
              <Trash2 :size="16" />
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- ページネーション UI -->
    <div v-if="totalPages > 1" class="mt-16 flex items-center justify-center gap-4">
      <button
        @click="setPage(Math.max(page - 1, 0))"
        :disabled="page === 0"
        class="p-4 rounded-2xl bg-white border border-teal-50 text-[#1a7a7a] disabled:opacity-30 disabled:cursor-not-allowed hover:bg-teal-50 transition-all shadow-sm"
      >
        <ChevronLeft :size="24" />
      </button>
      
      <div class="flex items-center gap-2">
        <button
          v-for="i in totalPages"
          :key="i"
          @click="setPage(i - 1)"
          :class="[
            'w-12 h-12 rounded-2xl font-black transition-all',
            page === i - 1
              ? 'bg-[#1a7a7a] text-white shadow-lg shadow-teal-200'
              : 'bg-white text-[#4a6b6b] hover:bg-teal-50 border border-teal-50'
          ]"
        >
          {{ i }}
        </button>
      </div>

      <button
        @click="setPage(page + 1)"
        :disabled="isPlaceholderData || page >= totalPages - 1"
        class="p-4 rounded-2xl bg-white border border-teal-50 text-[#1a7a7a] disabled:opacity-30 disabled:cursor-not-allowed hover:bg-teal-50 transition-all shadow-sm"
      >
        <ChevronRight :size="24" />
      </button>
    </div>
  </div>
</template>

// frontend/src/pages/KnowledgeList.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Edit, Trash2, Plus, BookOpen, Clock, ChevronRight, Loader2, ChevronLeft } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useQuery, useMutation, useQueryClient, keepPreviousData } from '@tanstack/react-query';
import type { Knowledge } from '../types/index';

// バックエンド API の場所を定義
const API_URL = 'http://localhost:8080/api/knowledge';

/**
 * ページネーション対応のデータ構造
 */
interface PageResponse<T> {
  content: T[];
  totalPages: number;
  totalElements: number;
  number: number; // 現在のページ番号
  size: number;   // 1ページあたりの件数
}

/**
 * API からナレッジ一覧を取得する関数（ページ指定対応）
 */
const fetchKnowledges = async (page: number): Promise<PageResponse<Knowledge>> => {
  const response = await fetch(`${API_URL}?page=${page}&size=6&sort=createdAt,desc`);
  if (!response.ok) throw new Error('Network response was not ok');
  return response.json();
};

/**
 * 【KnowledgeList コンポーネント】
 * 
 * TanStack Query を使用してページネーション対応のデータを取得・管理します。
 */
const KnowledgeList: React.FC = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  
  // 現在のページ番号の状態（0から開始）
  const [page, setPage] = useState(0);

  /**
   * [データ取得：useQuery]
   * - queryKey に page を含めることで、ページが変わるたびに再取得されます。
   * - placeholderData: keepPreviousData を使うことで、次のページ読み込み中も前のデータを表示し続けます。
   */
  const { data, isLoading, isError, isPlaceholderData } = useQuery({
    queryKey: ['knowledges', page],
    queryFn: () => fetchKnowledges(page),
    placeholderData: keepPreviousData,
  });

  const knowledges = data?.content || [];
  const totalPages = data?.totalPages || 0;

  /**
   * [データ削除：useMutation]
   */
  const deleteMutation = useMutation({
    mutationFn: async (id: number) => {
      await fetch(`${API_URL}/${id}`, { method: 'DELETE' });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['knowledges'] });
    },
  });

  /**
   * 削除ボタンが押された時の処理
   */
  const handleDelete = async (e: React.MouseEvent, id: number) => {
    e.stopPropagation(); 
    if (!window.confirm(t('common.confirm_delete'))) return;
    deleteMutation.mutate(id);
  };

  /**
   * 編集ボタンが押された時の処理
   */
  const handleEdit = (e: React.MouseEvent, id: number) => {
    e.stopPropagation(); // 詳細遷移を防止
    navigate(`/edit/${id}`); // 例：/edit/5 へ移動
  };

  /**
   * 本文の冒頭部分だけを抽出するヘルパー関数
   * 
   * @param text Markdown 形式の本文
   * @param maxLength 最大文字数
   */
  const getExcerpt = (text: string, maxLength: number = 150) => {
    // Markdown の記号（# や * など）を正規表現で簡易的に取り除きます
    const plainText = text.replace(/[#*`[\]()]/g, '');
    if (plainText.length <= maxLength) return plainText;
    return plainText.substring(0, maxLength) + '...';
  };

  return (
    <div className="max-w-6xl mx-auto">
      
      {/* ページ上部のヘッダーエリア */}
      <div className="flex items-center justify-between mb-10 px-2">
        <h2 className="text-3xl font-black text-[#0d3b3b] flex items-center gap-3">
          <span className="p-2 bg-[#1a7a7a] rounded-xl text-white shadow-lg shadow-teal-200">
            <BookOpen size={28} />
          </span>
          {t('knowledge.list_title')}
        </h2>
        
        <div className="flex items-center gap-4">
          {/* 登録件数を表示するバッジ */}
          <div className="flex items-center gap-2 px-4 py-2 bg-white rounded-full border border-teal-100 shadow-sm">
            <span className="w-2 h-2 bg-[#1a7a7a] rounded-full animate-pulse"></span>
            <span className="text-[#1a7a7a] text-sm font-black">
              {data?.totalElements || 0} <span className="text-xs font-bold text-[#4a6b6b]">{t('knowledge.items_count')}</span>
            </span>
          </div>
          
          {/* 新規作成ページへ飛ぶボタン */}
          <button
            onClick={() => navigate('/new')}
            className="flex items-center gap-2 px-6 py-2.5 bg-[#1a7a7a] hover:bg-[#0d3b3b] text-white rounded-xl font-bold transition-all shadow-lg shadow-teal-100 active:scale-95"
          >
            <Plus size={20} /> {t('sidebar.new_create')}
          </button>
        </div>
      </div>

      {/* 読み込み中・エラー時の表示 */}
      {isLoading ? (
        <div className="flex flex-col items-center justify-center py-32 text-[#1a7a7a]">
          <Loader2 size={48} className="animate-spin mb-4" />
          <p className="font-bold">{t('common.loading')}</p>
        </div>
      ) : isError ? (
        <div className="text-center py-32 bg-rose-50 rounded-[3rem] border-2 border-rose-100">
          <p className="text-rose-600 font-bold text-xl">データの取得に失敗しました。</p>
        </div>
      ) : knowledges.length === 0 ? (
        <div className="text-center py-32 bg-white rounded-[3rem] border-4 border-dashed border-teal-50">
          <div className="text-7xl mb-6 opacity-20">🍃</div>
          <p className="text-[#4a6b6b] font-bold text-2xl">{t('knowledge.no_items')}</p>
          <p className="text-slate-400 text-lg mt-3 font-medium">{t('knowledge.no_items_desc')}</p>
          <button
            onClick={() => navigate('/new')}
            className="mt-8 px-8 py-3 bg-teal-50 text-[#1a7a7a] rounded-2xl font-black hover:bg-teal-100 transition-all"
          >
            {t('knowledge.first_create')}
          </button>
        </div>
      ) : (
        /* カードを 2列（画面が狭い時は1列）で並べるグリッドレイアウト */
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {knowledges.map((k) => (
            <div 
              key={k.id} 
              onClick={() => navigate(`/knowledge/${k.id}`)} // カード全体をクリックで詳細画面へ
              className="group bg-white rounded-[2.5rem] p-8 shadow-xl shadow-teal-900/5 border border-teal-50 hover:border-[#1a7a7a]/20 hover:shadow-2xl hover:shadow-teal-900/10 transition-all duration-500 flex flex-col relative overflow-hidden cursor-pointer"
            >
              {/* 装飾用の背景の円（ホバーすると少し大きくなる） */}
              <div className="absolute top-0 right-0 w-40 h-40 bg-teal-50/30 rounded-full -mr-20 -mt-20 group-hover:scale-110 transition-transform duration-700"></div>
              
              <div className="flex-grow relative z-10">
                <h3 className="text-2xl font-black text-[#0d3b3b] mb-4 group-hover:text-[#1a7a7a] transition-colors line-clamp-2 leading-tight">
                  {k.title}
                </h3>
                {/* 抜粋テキストを表示 */}
                <p className="text-[#4a6b6b] leading-relaxed mb-6 line-clamp-3 font-medium text-sm">
                  {getExcerpt(k.content)}
                </p>
                <div className="flex items-center gap-1 text-[#1a7a7a] font-bold text-sm mb-8 group-hover:gap-2 transition-all">
                  {t('knowledge.view_detail')} <ChevronRight size={16} />
                </div>
              </div>
              
              {/* カード下部のメタ情報とボタン */}
              <div className="mt-auto pt-6 border-t border-teal-50 relative z-10 flex items-center justify-between">
                <div className="flex items-center gap-2 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">
                  <Clock size={12} />
                  {/* 日付を日本形式（YYYY/MM/DD）で表示 */}
                  {k.createdAt ? new Date(k.createdAt).toLocaleDateString('ja-JP') : '-'}
                </div>
                
                <div className="flex gap-2">
                  {/* 編集ボタン */}
                  <button
                    onClick={(e) => k.id && handleEdit(e, k.id)}
                    className="p-2.5 rounded-xl bg-amber-50 text-amber-700 hover:bg-amber-100 transition-all"
                    title={t('common.edit')}
                  >
                    <Edit size={16} />
                  </button>
                  {/* 削除ボタン */}
                  <button
                    onClick={(e) => k.id && handleDelete(e, k.id)}
                    className="p-2.5 rounded-xl bg-rose-50 text-red-600 hover:bg-rose-100 transition-all"
                    title={t('common.delete')}
                  >
                    <Trash2 size={16} />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ページネーション UI */}
      {totalPages > 1 && (
        <div className="mt-16 flex items-center justify-center gap-4">
          <button
            onClick={() => setPage((old) => Math.max(old - 1, 0))}
            disabled={page === 0}
            className="p-4 rounded-2xl bg-white border border-teal-50 text-[#1a7a7a] disabled:opacity-30 disabled:cursor-not-allowed hover:bg-teal-50 transition-all shadow-sm"
          >
            <ChevronLeft size={24} />
          </button>
          
          <div className="flex items-center gap-2">
            {[...Array(totalPages)].map((_, i) => (
              <button
                key={i}
                onClick={() => setPage(i)}
                className={`w-12 h-12 rounded-2xl font-black transition-all ${
                  page === i
                    ? 'bg-[#1a7a7a] text-white shadow-lg shadow-teal-200'
                    : 'bg-white text-[#4a6b6b] hover:bg-teal-50 border border-teal-50'
                }`}
              >
                {i + 1}
              </button>
            ))}
          </div>

          <button
            onClick={() => {
              if (!isPlaceholderData && page < totalPages - 1) {
                setPage((old) => old + 1);
              }
            }}
            disabled={isPlaceholderData || page >= totalPages - 1}
            className="p-4 rounded-2xl bg-white border border-teal-50 text-[#1a7a7a] disabled:opacity-30 disabled:cursor-not-allowed hover:bg-teal-50 transition-all shadow-sm"
          >
            <ChevronRight size={24} />
          </button>
        </div>
      )}
    </div>
  );
};

export default KnowledgeList;
